// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"
)

type Location struct {
	Bjdnumber          string
	Sggnumber          string
	Emdnumber          string
	Roadnumber         string
	Undergroundflag    int64
	Buildingmainnumber int64
	Buildingsubnumber  int64
	Sdname             string
	Sggname            sql.NullString
	Emdname            string
	Roadname           string
	Buildingname       sql.NullString
	Postalnumber       string
	Long               sql.NullFloat64
	Lat                sql.NullFloat64
	Crs                string
	X                  sql.NullFloat64
	Y                  sql.NullFloat64
	Validposition      int64
	Basedate           time.Time
	Datetimeadded      time.Time
}
