// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package sqlc

import (
	"context"
)

const getLocations = `-- name: GetLocations :one
SELECT bjdnumber, sggnumber, emdnumber, roadnumber, undergroundflag, buildingmainnumber, buildingsubnumber, sdname, sggname, emdname, roadname, buildingname, postalnumber, long, lat, crs, x, y, validposition, basedate, datetimeadded FROM locations
`

func (q *Queries) GetLocations(ctx context.Context) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocations)
	var i Location
	err := row.Scan(
		&i.Bjdnumber,
		&i.Sggnumber,
		&i.Emdnumber,
		&i.Roadnumber,
		&i.Undergroundflag,
		&i.Buildingmainnumber,
		&i.Buildingsubnumber,
		&i.Sdname,
		&i.Sggname,
		&i.Emdname,
		&i.Roadname,
		&i.Buildingname,
		&i.Postalnumber,
		&i.Long,
		&i.Lat,
		&i.Crs,
		&i.X,
		&i.Y,
		&i.Validposition,
		&i.Basedate,
		&i.Datetimeadded,
	)
	return i, err
}
